#!/bin/sh 

############ Auxiliary Function ########## 
error() {
	echo "$2"; exit "$1"; } 
##########################################

[ -f /etc/systemd/system/curfew.d.service ] && error 1 "/etc/systemd/system/curfew.d.service has existed. Please install curfew manually. exit 1.."
[ -f /etc/curfew.d ] && error 2 "/etc/curfew.d has existed. Please install curfew manually. exit 2.."

# Installation
echo "Copying curfew.d.surface to /etc/systemd/system/curfew.d.surface.";
cp "./unit/curfew.d.surface" "/etc/systemd/system/curfew.d.surface" && echo "done!" || echo "fail!" 
echo "Enabling curfew.d.surface";
systemctl enable curfew.d.surface && echo "done!" || echo "fail!" 
echo "Creating curfew.d and its content."; 
cp "./unit/curfew.d" "/etc/curfew.d" && echo "done!" || echo "fail!" 
echo "Making curfew.d executable.";
chmod +x /etc/curfew.d && echo "done!" || echo "fail!"

read -n 1 -s -r -p "Done. Press any key to continue."
echo ""

exit
