#!/bin/bash
## make sure your bash is after v4.0 for `readarray` to work.

mainDir="/root/curfew" 
mkdir -p $mainDir/log

#######################################################
#  Everything below will go to the file '$logfile'    # 
####################################################### 
logfile=$mainDir/log/$(date "+%Y-%m-%dT%H:%M:%S%z").txt
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3 RETURN
exec 1>$logfile 2>&1 
#######################################################



#######################################################
#  Read configs                                       # 
#######################################################
## note: readarray is supported only after bash 4.0
readarray -t app_list < $mainDir/list/app_list
readarray -t user_list < $mainDir/list/user_list
readarray -t url_list < $mainDir/list/url_list 
FunTimeStarts=160000 ; FunTimeEnds=163000 ;
MidnightWorkStarts=003000 ; MidnightWorkEnds=023000 ; 
#######################################################

#######################################################
#  Auxiliary functions                                #
#######################################################

if_within() {
	now=$(date +"%H%M%S") ; Start=$1 ; End=$2 ;
	[[ $Start < $End ]] && over_midnight=false || over_midnight=true
	if $over_midnight ; then
		[[ $Start < $now || $now < $End ]] && echo true || echo false
	else	[[ $Start < $now && $now < $End ]] && echo true || echo false
	fi
}

#######################################################
#  Actions                                            #
#######################################################

ban_url() {
	echo "execute: ban_url"
	if [[ ${#url_list[@]} != 0 ]] ; then
		for url in "${url_list[@]}"; do
			echo "ban_url $url"
			if ! grep -q $url /etc/hosts ; then
				echo "127.0.0.1 $url" >> /etc/hosts
			fi
		done
	fi
}

unban_url() {
	echo "execute: unban_url"
	if [[ ${#url_list[@]} != 0 ]] ; then
		for url in "${url_list[@]}"; do
			sed -i -e "/$url/d" /etc/hosts ; echo "unban_url $url"
		done
	fi
}

suspend_user() {
	echo "execute: suspend_user"
	if [[ ${#user_list[@]} != 0 ]] ; then
		for user in "${user_list[@]}"; do
			pkill -STOP -u "$user" ; echo "suspend_user $user"
		done
	fi
}

continue_user() {
	echo "execute: continue_user"
	if [[ ${#user_list[@]} != 0 ]] ; then
		for user in "${user_list[@]}"; do
			pkill -CONT -u "$user" ; echo "continue_user $user"
		done
	fi
}

kill_app() {
	echo "execute: kill_app"
	if [[ ${#app_list[@]} != 0 ]] ; then
		for app in "${app_list[@]}"; do
			pkill -f "$app" ; echo "kill_app $app"
		done
	fi
}

#######################################################



#######################################################
#  MAIN                                               #
#######################################################

main() {
	while true; do
		echo "current: $(date "+%Y-%m-%dT%H:%M:%S%z")"
		now=$(date +"%H%M%S") ; sleep 5 ;

		# if [[ $(date +%u) -lt 7 ]] ; then 					# ~~~restrictions on non-Sundays~~~
		if [[ $(date +%u) -lt 8 ]] ; then 					# restrictions everyday!

			if $(if_within $FunTimeStarts $FunTimeEnds) ; then		# during fun-time
				echo "message: fun-time on"
				unban_url
			elif $(if_within $MidnightWorkStarts $MidnightWorkEnds)	; then	# during midnight-work-time
				echo "message: midnightwork-time on"
				unban_url
				kill_app
			else								# during neither
				echo "message: neither fun-time nor midnightwork-time is on"
				ban_url
			fi
		

			
			if $(if_within $FunTimeEnds 000010) ; then
				echo "message: curfew on"
				suspend_user
			else				
				echo "message: curfew off"
				continue_user
			fi

		fi
	done
}

main

#######################################################

exit
